name: Fit24
description: Fit and Ripped 24.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+20

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  video_player: ^0.10.4
  flutter_spinkit: ^4.0.0
  swipedetector: ^1.2.0
  fl_animated_linechart: ^1.0.0
  splashscreen: ^1.2.0
  launch_review: ^2.0.0
  flare_flutter: ^1.7.3
  percent_indicator: ^2.1.1
  double_back_to_close_app: ^0.1.2
  flutter_calendar_carousel: ^1.4.9
  moor_flutter: ^3.0.0
  json_annotation: ^3.0.0
  provider: ^3.2.0
  screen: ^0.0.5
  intl: ^0.16.0
  intl_translation: ^0.17.7
  uuid: ^2.0.4
  flutter_local_notifications: ^0.9.1+2
  flutter_inapp_purchase: ^2.2.0
  fluttertoast: ^3.1.3
  shared_preferences: ^0.5.6+3
  path_provider: ^1.6.5
  path: ^1.6.4
  moor_ffi: ^0.7.0
  flutter_mailer: ^0.4.1+1

  #flutter email sender ios lib issues fix
  #rm -rf ios
  #flutter create -i swift .


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  page_indicator: ^0.3.0


  # GIT MANUAL PUSH !!!!
  #git add .
  #git commit -m 'message'
  #git push


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.1.9
  moor_generator: ^3.1.0
  build_runner: ^1.0.0
  json_serializable: ^3.3.0
  flutter_launcher_icons: ^0.7.4


flutter_native_splash:
  color: "FF6B4A"
  fill: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/video/bg_vide_start.mp4
    - assets/img/card_bg.png
    - assets/img/exercise_bg.png
    - assets/img/weight_line.png
    - assets/img/callories_img.png
    - assets/img/clock_img.png
    - assets/img/exercise_img.png
    - assets/img/profile_unpressed_icon.png
    - assets/img/plan_unpressed_icon.png
    - assets/img/exercises_unpressed_icon.png
    - assets/img/profile_pressed_icon.png
    - assets/img/plan_pressed_icon.png
    - assets/img/exercises_pressed_icon.png
    - assets/img/man_pressed_img.png
    - assets/img/woman_pressed_img.png
    - assets/img/man_unpressed_img.png
    - assets/img/woman_unpressed_img.png
    - assets/img/weight_selected_icon.png
    - assets/img/muscle_selected_icon.png
    - assets/img/jumper_selected_icon.png
    - assets/img/jumper_unselected_icon.png
    - assets/img/muscle_unselected_icon.png
    - assets/img/galery_sample_1.png
    - assets/img/galery_sample_2.png
    - assets/img/galery_sample_3.png
    - assets/img/weight_unselected_icon.png
    - assets/animated/anim.flr
    - assets/img/sample_img.png
    - assets/img/galery_sample_1.png
    - assets/img/galery_sample_2.png
    - assets/img/galery_sample_3.png
    - assets/img/done_img.png
    - assets/img/exercise_list_sample.png
    - assets/img/body_mass_index_img.png
    - assets/img/letter_image.png
    - assets/img/plane_icon.png
    - assets/img/logo.png
    - assets/img/sort_icon.png
    - assets/img/star_filled.png
    - assets/img/star_border.png
    - assets/img/circle.png
    - assets/img/orange_circle.png
    - assets/img/done.png
    - assets/img/selected_rect.png
    - assets/img/unselected_rect.png
    - assets/img/calendar_circle.png
    - assets/img/calendar_circle_filled.png
    - assets/img/loud_icon.png
    - assets/img/smile_img.png
    - assets/img/calendar_circle_whited.png
    - assets/img/cardio_1.png
    - assets/img/cardio_2.png
    - assets/img/cardio_3.png
    - assets/img/cardio_4.png
    - assets/img/cardio_5.png
    - assets/img/cardio_6.png
    - assets/img/cardio_7.png
    - assets/img/cardio_8.png
    - assets/img/cardio_9.png
    - assets/img/cardio_10.png
    - assets/img/cardio_11.png
    - assets/img/cardio_12.png
    - assets/img/core_1.png
    - assets/img/core_2.png
    - assets/img/core_3.png
    - assets/img/core_4.png
    - assets/img/core_5.png
    - assets/img/core_6.png
    - assets/img/core_7.png
    - assets/img/core_8.png
    - assets/img/core_9.png
    - assets/img/core_10.png
    - assets/img/core_11.png
    - assets/img/core_12.png
    - assets/img/upper_body_1.png
    - assets/img/upper_body_2.png
    - assets/img/upper_body_3.png
    - assets/img/upper_body_4.png
    - assets/img/upper_body_5.png
    - assets/img/upper_body_6.png
    - assets/img/upper_body_7.png
    - assets/img/upper_body_8.png
    - assets/img/upper_body_9.png
    - assets/img/upper_body_10.png
    - assets/img/upper_body_11.png
    - assets/img/upper_body_12.png
    - assets/img/lower_body_1.png
    - assets/img/lower_body_2.png
    - assets/img/lower_body_3.png
    - assets/img/lower_body_4.png
    - assets/img/lower_body_5.png
    - assets/img/lower_body_6.png
    - assets/img/lower_body_7.png
    - assets/img/lower_body_8.png
    - assets/img/lower_body_9.png
    - assets/img/lower_body_10.png
    - assets/img/lower_body_11.png
    - assets/img/lower_body_12.png
    - assets/img/full_body_1.png
    - assets/img/full_body_2.png
    - assets/img/full_body_3.png
    - assets/img/full_body_4.png
    - assets/img/full_body_5.png
    - assets/img/full_body_6.png
    - assets/img/full_body_7.png
    - assets/img/full_body_8.png
    - assets/img/full_body_9.png
    - assets/img/full_body_10.png
    - assets/img/full_body_11.png
    - assets/img/full_body_12.png
    - assets/video/1.mp4
    - assets/video/2.mp4
    - assets/video/3.mp4
    - assets/video/4.mp4
    - assets/video/5.mp4
    - assets/video/6.mp4
    - assets/video/7.mp4
    - assets/video/8.mp4
    - assets/video/10.mp4
    - assets/video/11.mp4
    - assets/video/12.mp4
    - assets/video/13.mp4
    - assets/video/14.mp4
    - assets/video/15.mp4
    - assets/video/16.mp4
    - assets/video/17.mp4
    - assets/video/18.mp4
    - assets/video/19.mp4
    - assets/video/20.mp4
    - assets/video/21.mp4
    - assets/video/22.mp4
    - assets/video/23.mp4
    - assets/video/24.mp4
    - assets/video/25.mp4
    - assets/video/26.mp4
    - assets/video/27.mp4
    - assets/video/28.mp4
    - assets/video/29.mp4
    - assets/video/30.mp4
    - assets/video/31.mp4
    - assets/video/32.mp4
    - assets/video/33.mp4
    - assets/video/34.mp4
    - assets/video/35.mp4
    - assets/video/36.mp4
    - assets/video/37.mp4
    - assets/video/38.mp4
    - assets/video/39.mp4
    - assets/video/40.mp4
    - assets/video/41.mp4
    - assets/video/42.mp4
    - assets/video/43.mp4
    - assets/video/44.mp4
    - assets/video/45.mp4
    - assets/video/46.mp4
    - assets/video/47.mp4
    - assets/video/48.mp4
    - assets/video/49.mp4
    - assets/video/50.mp4
    - assets/video/51.mp4
    - assets/video/52.mp4
    - assets/video/53.mp4
    - assets/video/54.mp4
    - assets/video/55.mp4
    - assets/video/56.mp4
    - assets/video/57.mp4
    - assets/video/58.mp4
    - assets/video/59.mp4
    - assets/video/60.mp4
    - assets/video/61.mp4
    - assets/video/62.mp4
    - assets/video/63.mp4
    - assets/video/64.mp4
    - assets/video/65.mp4
    - assets/video/66.mp4
    - assets/video/67.mp4
    - assets/video/68.mp4
    - assets/video/69.mp4
    - assets/video/70.mp4
    - assets/video/71.mp4
    - assets/video/73.mp4
    - assets/video/74.mp4
    - assets/video/75.mp4
    - assets/video/77.mp4
    - assets/video/78.mp4
    - assets/video/79.mp4
    - assets/video/80.mp4
    - assets/video/84.mp4
    - assets/video/85.mp4
    - assets/video/86.mp4
    - assets/video/87.mp4
    - assets/video/88.mp4
    - assets/video/89.mp4
    - assets/video/92.mp4
    - assets/video/93.mp4
    - assets/video/94.mp4
    - assets/video/95.mp4
    - assets/video/96.mp4
    - assets/video/97.mp4
    - assets/video/98.mp4
    - assets/video/99.mp4
    - assets/video/100.mp4
    - assets/video/101.mp4
    - assets/video/102.mp4
    - assets/video/103.mp4
    - assets/video/104.mp4
    - assets/video/105.mp4
    - assets/video/106.mp4
    - assets/video/107.mp4
    - assets/video/108.mp4
    - assets/video/110.mp4
    - assets/video/111.mp4
    - assets/video/112.mp4
    - assets/video/113.mp4
    - assets/video/114.mp4
    - assets/img/1.jpg
    - assets/img/2.jpg
    - assets/img/3.jpg
    - assets/img/4.jpg
    - assets/img/5.jpg
    - assets/img/6.jpg
    - assets/img/7.jpg
    - assets/img/8.jpg
    - assets/img/10.jpg
    - assets/img/11.jpg
    - assets/img/12.jpg
    - assets/img/13.jpg
    - assets/img/14.jpg
    - assets/img/15.jpg
    - assets/img/16.jpg
    - assets/img/17.jpg
    - assets/img/18.jpg
    - assets/img/19.jpg
    - assets/img/20.jpg
    - assets/img/21.jpg
    - assets/img/22.jpg
    - assets/img/23.jpg
    - assets/img/24.jpg
    - assets/img/25.jpg
    - assets/img/26.jpg
    - assets/img/27.jpg
    - assets/img/28.jpg
    - assets/img/29.jpg
    - assets/img/30.jpg
    - assets/img/31.jpg
    - assets/img/32.jpg
    - assets/img/33.jpg
    - assets/img/34.jpg
    - assets/img/35.jpg
    - assets/img/36.jpg
    - assets/img/37.jpg
    - assets/img/38.jpg
    - assets/img/39.jpg
    - assets/img/40.jpg
    - assets/img/41.jpg
    - assets/img/42.jpg
    - assets/img/43.jpg
    - assets/img/44.jpg
    - assets/img/45.jpg
    - assets/img/46.jpg
    - assets/img/47.jpg
    - assets/img/48.jpg
    - assets/img/49.jpg
    - assets/img/50.jpg
    - assets/img/51.jpg
    - assets/img/52.jpg
    - assets/img/53.jpg
    - assets/img/54.jpg
    - assets/img/55.jpg
    - assets/img/56.jpg
    - assets/img/57.jpg
    - assets/img/58.jpg
    - assets/img/59.jpg
    - assets/img/60.jpg
    - assets/img/61.jpg
    - assets/img/62.jpg
    - assets/img/63.jpg
    - assets/img/64.jpg
    - assets/img/65.jpg
    - assets/img/66.jpg
    - assets/img/67.jpg
    - assets/img/68.jpg
    - assets/img/69.jpg
    - assets/img/70.jpg
    - assets/img/71.jpg
    - assets/img/73.jpg
    - assets/img/74.jpg
    - assets/img/75.jpg
    - assets/img/77.jpg
    - assets/img/78.jpg
    - assets/img/79.jpg
    - assets/img/80.jpg
    - assets/img/84.jpg
    - assets/img/85.jpg
    - assets/img/86.jpg
    - assets/img/87.jpg
    - assets/img/88.jpg
    - assets/img/89.jpg
    - assets/img/92.jpg
    - assets/img/93.jpg
    - assets/img/94.jpg
    - assets/img/95.jpg
    - assets/img/96.jpg
    - assets/img/97.jpg
    - assets/img/98.jpg
    - assets/img/99.jpg
    - assets/img/100.jpg
    - assets/img/101.jpg
    - assets/img/102.jpg
    - assets/img/103.jpg
    - assets/img/104.jpg
    - assets/img/105.jpg
    - assets/img/106.jpg
    - assets/img/107.jpg
    - assets/img/108.jpg
    - assets/img/110.jpg
    - assets/img/111.jpg
    - assets/img/112.jpg
    - assets/img/113.jpg
    - assets/img/114.jpg
    - assets/img/workouts_pressed_icon.png
    - assets/img/workouts_unpressed_icon.png
    - assets/img/back_arrow.png
    - assets/img/sort.png
    - assets/img/big_ok.png
    - assets/img/kcal_in_card.png
    - assets/img/time_in_card.png
    - assets/img/exercise_complited.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Rubik-Regular
       fonts:
         - asset: fonts/Rubik-Regular.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
